# Generated by Django 4.0.2 on 2022-02-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('photo', models.ImageField(upload_to='carousel')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.BooleanField(blank=True, default=3.05, null=True)),
                ('cost', models.BooleanField(blank=True, default=1, null=True)),
            ],
        ),
    ]
