# Generated by Django 4.0.2 on 2022-02-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.05, max_digits=100000, null=True),
        ),
    ]
