# Generated by Django 4.0.2 on 2022-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_post_date_modified_post_date_send_post_post_box_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postman',
        ),
        migrations.AlterField(
            model_name='post',
            name='track_id',
            field=models.CharField(blank=True, default='91RsM', max_length=10),
        ),
    ]
