# Generated by Django 4.0.2 on 2022-03-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_sex'),
        ('post_app', '0007_remove_post_postman_alter_post_track_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date_send',)},
        ),
        migrations.AddField(
            model_name='post',
            name='post_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postman', to='account.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_box_num',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='track_id',
            field=models.CharField(blank=True, default='vKZGH', max_length=10),
        ),
    ]
