# Generated by Django 4.0.2 on 2022-03-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_alter_feedback_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='track_id',
            field=models.CharField(blank=True, default='KsuEC', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('track_id',)},
        ),
    ]
