# Generated by Django 4.0.2 on 2022-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_alter_post_track_id_alter_post_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='track_id',
            field=models.CharField(blank=True, default='aQruO', max_length=10),
        ),
    ]
