# Generated by Django 4.0.2 on 2022-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0010_post_seen_alter_post_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='track_id',
            field=models.CharField(blank=True, default='BMsut', max_length=10),
        ),
    ]
