# Generated by Django 4.0.2 on 2022-03-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_revoke_code'),
        ('post_app', '0012_alter_post_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='track_id',
            field=models.CharField(blank=True, default='G7NpM', max_length=10),
        ),
    ]
